# Compose version
version: "3"

services:
  # Brood API application
  brood:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bugout/brood:latest
    ports:
      - "0:7474"
    # Specify your local dev.env file
    env_file: ./brood.env
    environment:
      ALEMBIC_CONFIG: ../alembic.brood.ini
      BROOD_PORT: 7474
      BROOD_UVICORN_WORKERS: 1
      BROOD_ASGI_APP: brood.api:app
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://brood:7474/ping"]
    #   interval: 5s
    #   timeout: 1s
    #   retries: 2
    #   start_period: 2s
    depends_on:
      db:
        condition: service_healthy

  # DB postgres application
  db:
    image: postgres:13
    ports:
      - "0:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "SELECT 1;"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 2s