"""subscription units and types

Revision ID: 1ff0db1a7b28
Revises: fc553de1b848
Create Date: 2021-03-17 09:12:21.176822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ff0db1a7b28'
down_revision = 'fc553de1b848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('default_units', sa.Integer(), nullable=True))
    op.execute("UPDATE subscription_plans SET default_units = 5 WHERE stripe_product_id IS NULL AND stripe_price_id IS NULL")

    op.add_column('subscription_plans', sa.Column('plan_type', sa.String(), nullable=True))
    op.execute("UPDATE subscription_plans SET plan_type = 'seats'")
    op.alter_column("subscription_plans", "plan_type", nullable=False)

    op.add_column('subscriptions', sa.Column('units', sa.Integer(), nullable=True))
    op.execute("UPDATE subscriptions SET units = seats")
    op.alter_column("subscriptions", "units", nullable=False)

    op.drop_column('subscriptions', 'seats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('seats', sa.Integer(), autoincrement=False, nullable=True))
    op.execute("UPDATE subscriptions SET seats = units")
    op.alter_column("subscriptions", "seats", nullable=False)

    op.drop_column('subscriptions', 'units')
    op.drop_column('subscription_plans', 'plan_type')
    op.drop_column('subscription_plans', 'default_units')
    # ### end Alembic commands ###
