"""Added user_group_limits

Revision ID: 2279d61d112d
Revises: ea9c6f4e526f
Create Date: 2021-02-24 17:09:33.144413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2279d61d112d"
down_revision = "ea9c6f4e526f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_group_limits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("group_limit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_group_limits_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_group_limits")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_group_limits_user_id")),
    )
    # ### end Alembic commands ###
    set_limits_query = """
INSERT INTO user_group_limits (user_id, group_limit) SELECT id as user_id, 15 as group_limit from users;
"""
    op.execute(set_limits_query)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_group_limits")
    # ### end Alembic commands ###
