"""Application table for resources and users

Revision ID: 272ba3d48bb4
Revises: b1c643d0d50a
Create Date: 2021-07-13 11:36:44.370553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '272ba3d48bb4'
down_revision = 'b1c643d0d50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_applications_group_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('id', name=op.f('uq_applications_id'))
    )
    op.add_column('users', sa.Column('application_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_users_applications_id', 'users', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_applications_id', 'users', type_='foreignkey')
    op.drop_column('users', 'application_id')
    op.drop_table('applications')
    # ### end Alembic commands ###
