"""Time fields for Group, group_name -> name, reset_passwords on delete cascade

Revision ID: 488cd5a21817
Revises: 84e5ee946489
Create Date: 2020-12-21 12:18:27.112263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488cd5a21817'
down_revision = '84e5ee946489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False))
    op.add_column('groups', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False))

    # Manual part
    op.execute("UPDATE groups SET name = group_name;")
    op.alter_column("groups", "name", nullable=False)
    
    op.drop_constraint('uq_groups_group_name', 'groups', type_='unique')
    op.drop_column('groups', 'group_name')
    op.drop_constraint('fk_reset_passwords_user_id', 'reset_passwords', type_='foreignkey')
    op.create_foreign_key('fk_reset_passwords_user_id', 'reset_passwords', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reset_passwords_user_id', 'reset_passwords', type_='foreignkey')
    op.create_foreign_key('fk_reset_passwords_user_id', 'reset_passwords', 'users', ['user_id'], ['id'])
    op.add_column('groups', sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_groups_group_name', 'groups', ['group_name'])
    
    # Manual part
    op.execute("UPDATE groups SET group_name = name")
    op.alter_column("groups", "group_name", nullable=False)
    
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'name')
    op.drop_column('groups', 'created_at')
    # ### end Alembic commands ###
