"""Resource permissions simplification

Revision ID: 646fcad41144
Revises: 6bc0ee79a3ce
Create Date: 2024-01-25 06:23:58.687448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '646fcad41144'
down_revision = '6bc0ee79a3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('admin', 'create', 'read', 'update', 'delete', name='resource_permissions_enum').create(op.get_bind())
    op.add_column('resource_holder_permissions', sa.Column('permission', sa.Enum('admin', 'create', 'read', 'update', 'delete', name='resource_permissions_enum'), nullable=True))
    op.drop_constraint('uq_resource_holder_permissions_user_id', 'resource_holder_permissions', type_='unique')
    op.create_index('uq_resource_holder_permissions_group_id_resource_id_permission', 'resource_holder_permissions', ['group_id', 'resource_id', 'permission'], unique=True, postgresql_where=sa.text('group_id IS NOT NULL'))
    op.create_index('uq_resource_holder_permissions_user_id_resource_id_permission', 'resource_holder_permissions', ['user_id', 'resource_id', 'permission'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))

    # Fulfill column
    op.execute("UPDATE resource_holder_permissions SET permission = resource_permissions.permission::resource_permissions_enum FROM resource_permissions WHERE resource_permissions.id = resource_holder_permissions.permission_id")

    op.alter_column("resource_holder_permissions", "permission", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    op.drop_index('uq_resource_holder_permissions_user_id_resource_id_permission', table_name='resource_holder_permissions', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_resource_holder_permissions_group_id_resource_id_permission', table_name='resource_holder_permissions', postgresql_where=sa.text('group_id IS NOT NULL'))
    op.create_unique_constraint('uq_resource_holder_permissions_user_id', 'resource_holder_permissions', ['user_id', 'group_id', 'resource_id', 'permission_id'])
    op.drop_column('resource_holder_permissions', 'permission')
    # ### end Alembic commands ###
