"""new table for groups

Revision ID: 8915acdd2939
Revises: 35738b48b928
Create Date: 2020-09-09 08:51:45.880519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8915acdd2939'
down_revision = '35738b48b928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('group_name', name=op.f('uq_groups_group_name')),
    sa.UniqueConstraint('id', name=op.f('uq_groups_id'))
    )
    op.create_table('group_users',
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_type', sa.Enum('owner', 'member', name='user_type'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_users_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_group_users_user_id'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_group_users'))
    )
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    op.create_unique_constraint(op.f('uq_verification_emails_id'), 'verification_emails', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_verification_emails_id'), 'verification_emails', type_='unique')
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_table('group_users')
    op.drop_table('groups')
    sa.Enum('owner', 'member', name='user_type').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
