"""Group with application ID

Revision ID: c3ded8ff2ea8
Revises: 746fcad41145
Create Date: 2024-08-05 18:39:23.470012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3ded8ff2ea8'
down_revision = '746fcad41145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('application_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_groups_applications_id', 'groups', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'application_id')
    # ### end Alembic commands ###
