"""Token touched_at column

Revision ID: d44da2eb423b
Revises: 6bc0ee79a3ce
Create Date: 2023-05-29 12:08:08.412359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44da2eb423b'
down_revision = '6bc0ee79a3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('touched_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False))

    # Manual part
    op.execute("""CREATE FUNCTION fx_tokens_select_with_touch(t_id UUID) 
    RETURNS TABLE(id uuid,
        user_id uuid,
        active boolean,
        token_type token_type,
        note varchar,
        restricted boolean,
        created_at timestamptz,
        touched_at timestamptz,
        updated_at timestamptz) LANGUAGE plpgsql VOLATILE AS $func$
BEGIN
    UPDATE tokens SET touched_at = NOW() WHERE tokens.id = t_id;
    RETURN QUERY(SELECT tokens.id,
        tokens.user_id,
        tokens.active,
        tokens.token_type,
        tokens.note,
        tokens.restricted,
        tokens.created_at,
        tokens.touched_at,
        tokens.updated_at FROM tokens WHERE tokens.id = t_id);
END;
$func$;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'touched_at')

    # Manual part
    op.execute("DROP FUNCTION fx_tokens_select_with_touch;")
    # ### end Alembic commands ###
