"""parent group column

Revision ID: d5ee05f701ab
Revises: 2d6d58fd7cc9
Create Date: 2021-02-11 10:43:30.243377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5ee05f701ab'
down_revision = '2d6d58fd7cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('parent', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_groups_parent', 'groups', 'groups', ['parent'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_groups_parent', 'groups', type_='foreignkey')
    op.drop_column('groups', 'parent')
    # ### end Alembic commands ###
