"""invite to group

Revision ID: fc553de1b848
Revises: d5ee05f701ab
Create Date: 2021-03-26 10:05:27.435793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc553de1b848'
down_revision = 'd5ee05f701ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invites',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('initiator_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('invited_email', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', statement_timestamp())"), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_invites_group_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], name='fk_group_invites_initiator_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_invites')),
    sa.UniqueConstraint('id', name=op.f('uq_group_invites_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_invites')
    # ### end Alembic commands ###
