/*
Brood database model.
*/
package brood

import (
	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID `json:"id"`
	Username        string    `json:"username"`
	Email           string    `json:"email"`
	NormalizedEmail string    `json:"normalized_email"`
	PasswordHash    string    `json:"password_hash"`
	AuthType        string    `json:"auth_type"`
	Verified        bool      `json:"verified"`
	CreatedAt       string    `json:"created_at"`
	UpdatedAt       string    `json:"updated_at"`
	Autogenerated   bool      `json:"autogenerated"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	ApplicationID   uuid.UUID `json:"application_id"`
}
